"""updates

Revision ID: c6e95f0c9a06
Revises: d35127f0dc57
Create Date: 2024-03-10 11:17:14.544203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6e95f0c9a06'
down_revision: Union[str, None] = 'd35127f0dc57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('credit_hours', sa.Integer(), nullable=True))
    op.drop_column('programs', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('duration', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('programs', 'credit_hours')
    # ### end Alembic commands ###
