"""updates

Revision ID: e99673ef15b6
Revises: 5716b8e96be6
Create Date: 2024-03-10 13:28:11.179281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e99673ef15b6'
down_revision: Union[str, None] = '5716b8e96be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('current_year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'current_year')
    # ### end Alembic commands ###
