from .role import Role
from .user import User
from .program import Program
from .course import Course
from .semester import Semester
from .program_course import ProgramCourse
from .grade import Grade
from .student import Student
from .student_course import StudentCourse
from .exam_score import ExamScore
